export enum FieldType {
    text = 'text',
    password = 'password',
    color = 'color',
    range = 'range',
    number = 'number',
    url = 'url',
    email = 'email',
    tel = 'tel',
    textArea = 'text-area',
    date = 'date',
    time = 'time',
    dropdown = 'drop-down',
    slideToggle = 'slide-toggle',
    file = 'file',
    checkbox = 'checkbox',
    radio = 'radio',
    array = 'array',
    group = 'group'
}
