export const AppLiteralConsts = {
  actionButton: {
    create: 'create',
    add: 'add',
    edit: 'edit',
    delete: 'delete',
    view: 'view',
    sortChange: 'sortChange',
    pageChange: 'pageChange',
    search: 'search',
    sortBy: '__utcLastUpdatedOn',
    export: 'export',
  },
  alertMessage: {
    postSuccess: 'Created successfully!',
    updateSuccess: 'Updated successfully!',
    deleteSuccess: 'Deleted successfully!',
    confirmation: 'Are you sure you want to do this?',
    actionNotSupported: 'This Action is not supported.',
    error: 'Something went wrong!',
    invalidURL: 'Invalid URL.',
  },
  dataTypes: {
    type: 'type',
    string: 'string',
    object: 'object',
    array: 'array',
    datetimeLocal: 'datetime-local',
    date: 'date',
    group: 'group',
    boolean: 'boolean',
  },
  fieldType: {
    text: 'text',
    password: 'password',
    number: 'number',
    url: 'url',
    email: 'email',
    tel: 'tel',
    textarea: 'text-area',
    date: 'date',
    datetime: 'date-time',
    time: 'time',
    dropdown: 'dropdown',
    slideToggle: 'slide-toggle',
    file: 'file',
    checkbox: 'checkbox',
    radio: 'radio',
    array: 'array',
    group: 'group',
  },
  validators: {
    min: 'min',
    max: 'max',
    required: 'required',
    requiredTrue: 'requiredTrue',
    email: 'email',
    minLength: 'minLength',
    maxLength: 'maxLength',
    nullValidator: 'nullValidator',
    jsonValidator: 'jsonValidator',
    pattern: 'pattern',
    duplicateValidator: 'duplicateValidator',
  },
  formStatus: {
    valid: 'VALID',
    invalid: 'INVALID',
  },
  toast: {
    success: 'success-snackbar',
    accent: 'accent-snackbar',
    error: 'error-snackbar',
    matToolbar: 'mat-toolbar',
    close: 'Close',
    toastPostionBottomCenter: 'toast-bottom-center',
  },
  sheet: {
    excel: 'xlsx',
    csv: 'csv',
  },
  theme: {
    primary: 'primary',
  },
  dateFormat: {
    yearMonthDay: 'yyyy-MM-dd HH:mm',
  },
  imgIconPath: {
    swipeCard: '../../../../assets/images/icons/swipe-card-white.svg',
    merchant: '../../../../assets/images/icons/merchant-white.svg',
    bank: '../../../../assets/images/icons/bank-account-white.svg',
    gateway: '../../../../assets/images/icons/gateway-white.svg',
    card: '../../../../assets/images/icons/cards-white.svg',
    region: '../../../../assets/images/icons/region-white.svg',
    settings: '../../../../assets/images/icons/settings-white.svg',
  },
  iconName: {
    wallet: 'account_balance_wallet',
    search: 'search',
  },
  placeholder: {
    search: 'Search',
    active: 'Active',
  },
};
